<a href="https://colab.research.google.com/github/Vaycold/tensorflow_tutorial/blob/main/%2314.%ED%85%90%EC%84%9C%EC%99%80%20%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 텐서와 연산

In [1]:
import tensorflow as tf

    텐서 = 다차원 배열

In [2]:
print(tf.add(1,2))
print(tf.add([1,2],[3,4]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)


In [3]:
print(tf.square(5))

tf.Tensor(25, shape=(), dtype=int32)


In [4]:
print(tf.reduce_sum([1,2,3]))

tf.Tensor(6, shape=(), dtype=int32)


In [5]:
tf.add(1,2,3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [6]:
tf.reduce_sum([1,2,10])

<tf.Tensor: shape=(), dtype=int32, numpy=13>

In [7]:
tf.add(1,2,10)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [8]:
print(tf.add(1,2,10))

tf.Tensor(3, shape=(), dtype=int32)


In [9]:
x = tf.matmul([[1]],[[2,3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [10]:
# 넘파이 호환성

import numpy as np
ndarray = np.ones([3,3])

tensor = tf.multiply(ndarray,42)
print(ndarray)
print('')
print(tensor)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)


In [11]:
# 넘파이 연산은 자동적으로 텐서를 넘파이 배열로 변환
print(np.add(tensor,1))

[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]


In [12]:
print(np.add(tensor,2))

[[44. 44. 44.]
 [44. 44. 44.]
 [44. 44. 44.]]


In [13]:
# .numpy() method
print(tensor.numpy())
print(type(tensor.numpy()))

[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]
<class 'numpy.ndarray'>


In [14]:
# GPU 가속
'''
대부분의 텐서플로 연산 : GPU 사용하여 가속화 
연산에 의해 생성된 텐서는 전형적으로 연산이 실행된 장치의 메모리에 의해 실행
'''
X = tf.random.uniform([3,3])
X

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.68243015, 0.3990053 , 0.38593638],
       [0.55810857, 0.18742335, 0.48533738],
       [0.3942951 , 0.7395297 , 0.5493897 ]], dtype=float32)>

In [15]:
import warnings

print('GPU 사용이 가능한가 : ')
print(tf.test.is_gpu_available())

print()
print('텐서가 GPU  #0에 있는가')
print(X.device.endswith('GPU:0'))

GPU 사용이 가능한가 : 
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
False

텐서가 GPU  #0에 있는가
False


In [36]:
# 데이터셋
''' 
모델에 데이터를 제공하기 위한 파이프라인 구축위해 tf.data.Dataset API 사용
tf.data.Dataset : 모델 훈련, 평가 루프 제공
간단하고 재사용 가능한 모듈로부터 복잡한 입력 파이프라인을 구축하기 위해 사용
 
 - Dataset.from_tensors
 - Dataset.from_tensor_slices
 - TextLineDataset
 - TFRecordDataset

'''
ds_tensors = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6])
ds_tensors

<TensorSliceDataset shapes: (), types: tf.int32>

In [47]:
# csv 파일 생성

import tempfile
_, filename = tempfile.mkstemp()
with open(filename, 'w') as f :
    f.write('''Line 1
    Line2
    Line3
    '''
    )

In [48]:
ds_file = tf.data.TextLineDataset(filename)
ds_file

<TextLineDatasetV2 shapes: (), types: tf.string>

In [49]:
# 변환적용
'''
map, batch, shuffle 과 같은 변환함수 사용
'''
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)

ds_file = ds_file.batch(2)

In [38]:
# 반복

print('ds_tensors 요소 : ')
for x in ds_tensors :
    print(x)

ds_tensors 요소 : 
tf.Tensor([1 9], shape=(2,), dtype=int32)
tf.Tensor([ 4 16], shape=(2,), dtype=int32)
tf.Tensor([36 25], shape=(2,), dtype=int32)


In [50]:
print('ds_file 요소 :')
for x in ds_file :
    print(x)

ds_file 요소 :
tf.Tensor([b'Line 1' b'    Line2'], shape=(2,), dtype=string)
tf.Tensor([b'    Line3' b'    '], shape=(2,), dtype=string)
