<a href="https://colab.research.google.com/github/Vaycold/tensorflow_tutorial/blob/main/%2314.%ED%85%90%EC%84%9C%EC%99%80%20%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 텐서와 연산

In [1]:
import tensorflow as tf

    텐서 = 다차원 배열

In [3]:
print(tf.add(1,2))
print(tf.add([1,2],[3,4]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)


In [4]:
print(tf.square(5))

tf.Tensor(25, shape=(), dtype=int32)


In [5]:
print(tf.reduce_sum([1,2,3]))

tf.Tensor(6, shape=(), dtype=int32)


In [13]:
tf.add(1,2,3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [16]:
tf.reduce_sum([1,2,10])

<tf.Tensor: shape=(), dtype=int32, numpy=13>

In [17]:
tf.add(1,2,10)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [18]:
print(tf.add(1,2,10))

tf.Tensor(3, shape=(), dtype=int32)


In [20]:
x = tf.matmul([[1]],[[2,3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [23]:
# 넘파이 호환성

import numpy as np
ndarray = np.ones([3,3])

tensor = tf.multiply(ndarray,42)
print(ndarray)
print('')
print(tensor)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)


In [24]:
# 넘파이 연산은 자동적으로 텐서를 넘파이 배열로 변환
print(np.add(tensor,1))

[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]


In [25]:
print(np.add(tensor,2))

[[44. 44. 44.]
 [44. 44. 44.]
 [44. 44. 44.]]


In [28]:
# .numpy() method
print(tensor.numpy())
print(type(tensor.numpy()))

[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]
<class 'numpy.ndarray'>


In [32]:
# GPU 가속
'''
대부분의 텐서플로 연산 : GPU 사용하여 가속화 
연산에 의해 생성된 텐서는 전형적으로 연산이 실행된 장치의 메모리에 의해 실행
'''
X = tf.random.uniform([3,3])
X

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.06876707, 0.1007489 , 0.56915617],
       [0.30564535, 0.3466264 , 0.9945744 ],
       [0.20260644, 0.32500672, 0.5696734 ]], dtype=float32)>

In [36]:
import warnings

print('GPU 사용이 가능한가 : ')
print(tf.test.is_gpu_available())

print()
print('텐서가 GPU  #0에 있는가')
print(X.device.endswith('GPU:0'))

GPU 사용이 가능한가 : 
False

텐서가 GPU  #0에 있는가
False
