<a href="https://colab.research.google.com/github/Vaycold/tensorflow_tutorial/blob/main/%2315.%EB%A7%9E%EC%B6%A4%EB%A0%88%EC%9D%B4%EC%96%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# 층 유용한 연산자 집합
'''
tf.keras.layers 패키지에서 층 = 객체
대부분의 layer는 첫 번째 인수로 출력차원 또는 채널을 가짐

'''
import tensorflow as tf

layer = tf.keras.layers.Dense(100) # 첫 번째 인수 = 출력차원
layer = tf.keras.layers.Dense(10, input_shape = (None, 5))

In [16]:
# 층을 사용하려면 간단하게 호출
print(tf.zeros([10,5]))
print(layer(tf.zeros([10,5])))
'''
shape 을 보면 (10,10)임을 알 수 있음. layer는 객체로 출력차원이 10임. 

input으로 (10,5)가 들어가서 output은 (10,10)으로 나오게 된것임.
'''
pass

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(10, 5), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)


In [19]:
print(layer(tf.zeros([3,5])))
'''
input으로(3,5)가 들어가면
output은 (3,10)으로 나오게 됨.
'''
pass

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(3, 10), dtype=float32)


In [20]:
''' 
layer 는 유용한 메서드를 많이 가지고 있음.
예를 들어, layer.variables : 사용하여 층안에 있는 모든 변수를 확인할 수 있으며
layer.trainable_variables를 사용하여 훈련 가능한 변수를 확인 가능
전결합층은 가중치와 편향을 위한 변수를 가짐
'''
layer.variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.13885689, -0.20110026, -0.15525854,  0.354782  , -0.10672539,
          0.27789402,  0.03570175,  0.04746091, -0.19021085,  0.5472258 ],
        [ 0.39179796,  0.5092067 , -0.53714234, -0.13051206, -0.08359736,
          0.21843755,  0.00487202,  0.06907684,  0.4987505 ,  0.5849722 ],
        [-0.28039876,  0.12176013,  0.42848903,  0.31001568, -0.10764474,
         -0.09984124,  0.18813765,  0.18938738,  0.43532556, -0.06711006],
        [ 0.05563277,  0.10312396,  0.22630197,  0.39554304, -0.27480704,
         -0.47659504, -0.33824643,  0.2566579 , -0.38874966, -0.25512937],
        [-0.15735888, -0.05412996,  0.59526235,  0.30768508, -0.17008185,
         -0.46637696, -0.05657429,  0.50611895,  0.26037544,  0.15838486]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [21]:
# 객체의 속성을 통해 편리하게 접근 가능
layer.kernel, layer.bias

(<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.13885689, -0.20110026, -0.15525854,  0.354782  , -0.10672539,
          0.27789402,  0.03570175,  0.04746091, -0.19021085,  0.5472258 ],
        [ 0.39179796,  0.5092067 , -0.53714234, -0.13051206, -0.08359736,
          0.21843755,  0.00487202,  0.06907684,  0.4987505 ,  0.5849722 ],
        [-0.28039876,  0.12176013,  0.42848903,  0.31001568, -0.10764474,
         -0.09984124,  0.18813765,  0.18938738,  0.43532556, -0.06711006],
        [ 0.05563277,  0.10312396,  0.22630197,  0.39554304, -0.27480704,
         -0.47659504, -0.33824643,  0.2566579 , -0.38874966, -0.25512937],
        [-0.15735888, -0.05412996,  0.59526235,  0.30768508, -0.17008185,
         -0.46637696, -0.05657429,  0.50611895,  0.26037544,  0.15838486]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

## 사용자 정의 층 구현
    
    사용자 정의 층을 구현하는 가장 좋은 방법은 tf.keras.Layer 클래스를 상송하고 다음과 같이 구현

    - __init__ : 층에 필요한 매개 변수를 입력받는다.
    - build, 입력 텐서의 크기를 얻고 남은 초기화 진행
    - call, 정방향 연산을 진행할 수 있다.

    

In [22]:
# 변수를 생성하기 위해 build가 호출되길 기다릴 필요가 없음.
# 또한 변수를 __init__에 생성 가능.
# 그러나 변수를 생성하는 유리한 점은 층이 작동할 입력의 크기를 기준으로 나중에 변수를 만들 수 있다는 것
# 반면에 __init__에 변수를 생성하는 것은 변수 생성에 필요한 크기가 명시적으로 지정되어야 함을 의미함.

class MyDenseLayer(tf.keras.layers.Layer) :
    def __init__(self, num_outputs) :
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs
    
    def build(self, input_shape) :
        self.kernel = self.add_variable('kernel' ,
                                        shape = [int(input_shape[-1]),
                                                 self.num_outputs])
    
    def call(self, input) :
        return tf.matmul(input, self.kernel)


layer = MyDenseLayer(10)
print(layer(tf.zeros([10,5])))
print(layer.trainable_variables)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
[<tf.Variable 'my_dense_layer/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[-0.4898984 , -0.24164188, -0.2931902 ,  0.30400658,  0.15894562,
        -0.44418156, -0.20304376,  0.6261247 , -0.4352666 , -0.5857925 ],
       [ 0.4695689 ,  0.28184497, -0.15932456, -0.061243  , -0.58519834,
         0.29931223, -0.06109029,  0.44492048,  0.5924743 ,  0.23563594],
       [-0.40538004,  0.01997775, -0.05343199, -0.41960716, -0.52288914,
        -0.39451855, -0.1885635 , -0.1628342 ,  0.28503776,  0.39066154],
       [ 0.42540413,  0.22433698, -0.15229735,  0.01007962,  0.42257077,
        -0.48552793,  0.30263352, -0

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/base_layer.py:2191: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  warnings.warn('`layer.add_variable` is deprecated and '


## 모델 층 구성

    머신러닝 모델에서 재미있는 많은 것들은 기존의 층을 조합하여 구현

    다른 층을 포함한 모델을 만들기 위해 사용하는 메인 클래스는 tf.keras.Model 상속하여 구현
    

In [25]:
class ResnetIdentityBlock(tf.keras.Model) :
    def __init__(self, kernel_size, filters) :
        super(ResnetIdentityBlock, self).__init__(name='')
        filters1, filters2, filters3 = filters

        self.conv2a = tf.keras.layers.Conv2D(filters1, (1,1))
        self.bn2a   = tf.keras.layers.BatchNormalization()

        self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
        self.bn2b   = tf.keras.layers.BatchNormalization()

        self.conv2c = tf.keras.layers.Conv2D(filters3, (1,1))
        self.bn2c   = tf.keras.layers.BatchNormalization()
    
    def call(self, input_tensor, training = False) :
        x = self.conv2a(input_tensor)
        x = self.bn2a(x, training = training)
        x = tf.nn.relu(x)

        x = self.conv2b(x)
        x = self.bn2b(x, training = training)
        x = tf.nn.relu(x)

        x = self.conv2c(x)
        x = self.bn2c(x, training = training)

        x += input_tensor
        return tf.nn.relu(x)

block = ResnetIdentityBlock(1, [1,2,3])
print(block(tf.zeros([1,2,3,3])))

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)


In [26]:
# 그러나 대부분의 경우에 많은 층으로 구성된 모델은 단순하게 순서대로 층을 하나씩 호출
my_seq = tf.keras.Sequential(
    [
     tf.keras.layers.Conv2D(1, (1,1), input_shape=(None, None, 3)),
     tf.keras.layers.BatchNormalization(),
     tf.keras.layers.Conv2D(2,1, padding='same'),
     tf.keras.layers.BatchNormalization(),
     tf.keras.layers.Conv2D(3, (1,1)),
     tf.keras.layers.BatchNormalization()
     ])

my_seq(tf.zeros([1,2,3,3]))


<tf.Tensor: shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>